"project_id": "622506"
"api_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJ3UUVxdmhVM3ZMT2EyWGljbVV5VCIsImp0aSI6ImNhZjZhNzI3NDQ4ZTdhZjk0ZmMwMGFiYjY2ZWViNjE4MGVhZDBjNDcyNDRjZGQ5NWNjNTg4MGUwZGNkZDU5ZjYzNWY5Njg5MGMzMWI1YzNiIiwiaWF0IjoxNjk4MDY3ODkyLjE1NTc0MSwibmJmIjoxNjk4MDY3ODkyLjE1NTc0NCwiZXhwIjoxNzI5NjAzODkyLjA1MzY5Nywic3ViIjoiMTYwNTY2MTYiLCJzY29wZXMiOlsicHJvamVjdCJdLCJkb21haW4iOm51bGwsImFzc29jaWF0aW9ucyI6WyIqIl0sInNlc3Npb24iOjB9.G1D8xLL53NqQZO3HP5kQdiM8_-hzxWqsxCjS2zdsJEpEM_5eL9B3Kio0thXfBiLM-3FZELF_jngq85OOdgQUUcgUsW4rusTjzufLkWo97y0Q5UjT9D91vgfaoc-ViuvQCKVqpPNJDC2KaM4OTsffksmC5YJWmdtQjvWepHWuz0O_m53kWQzHvYBaXppB4AdZtiFiruVKNErtHd60p_Ndl_15BfmhHwnGBKelmnTYUYpdO9y_h25TaVChUpxnAPlmbnM5bVFkl8T3o3cWT_JGtmcOtIXQJBVcHNNnEVne39IZGGCmA5N4ljNiWd9f1k6ALiJCAA-8e9bl8CUCcfUdEhlqgc30YfFPZIGpmozH89xDB5MNCHs3Z4QRi7dXikeFBX9ISxysFBNWLDZxcVln0ENWGO19RLdBxrqaOTa_6FzVAlUHb6_AwoZiLLjaLZ5CVh2zFY6mhhxxtJFMuX6KY3Jz0acFly2-IwV6r4VO4FSUYicsoL6ZYGdbeR9oqOHBQrfwDFEE34XnuMbDU92mkW_AVyDaGCsmuomM37qYmZRrvJYR4qUdYRpFvPM3FEx3befdVTBYG_fYPCKSZ1xsnX-eMDALxiDlhbN0-Px73TzrvKjlojAt2rk-UtfJgveybHOcKUaO_AY_c5Av6yL-CJRfhrCpqX-hR6X6d4mvlLE"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true
files: [
  {
    "source": "",
    "translation": ""
  }
]
